"""
Script to create a new user in the database.
Run this script to create an admin user for login.

Usage:
    python create_user.py
"""

import os
import sys
import psycopg2
from werkzeug.security import generate_password_hash
from dotenv import load_dotenv

# Load environment variables (check current dir and parent dir)
load_dotenv()
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', '.env'))

# Database configuration
DB_CONFIG = {
    'host': os.getenv('DB_HOST', 'localhost'),
    'port': os.getenv('DB_PORT', '5432'),
    'user': os.getenv('DB_USER', 'postgres'),
    'password': os.getenv('DB_PASS', ''),
    'database': os.getenv('DB_NAME', 'facebook_aggregator')
}


def create_user(email, password, name=None, is_admin=False):
    """Create a new user in the database"""
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        cursor = conn.cursor()
        
        # Check if user already exists
        cursor.execute("SELECT id FROM users WHERE email = %s", (email,))
        existing_user = cursor.fetchone()
        if existing_user:
            print(f"User with email {email} already exists!")
            return False, None
        
        # Generate password hash
        password_hash = generate_password_hash(password)
        
        # Insert new user (UUID will be auto-generated by database)
        cursor.execute("""
            INSERT INTO users (email, password_hash, name, is_active, is_admin)
            VALUES (%s, %s, %s, %s, %s)
            RETURNING id
        """, (email, password_hash, name or email.split('@')[0], True, is_admin))
        
        user_id = cursor.fetchone()[0]
        conn.commit()
        cursor.close()
        conn.close()
        
        print(f"User '{email}' created successfully!")
        return True, user_id
        
    except psycopg2.Error as e:
        print(f"Database error: {e}")
        return False, None
    except Exception as e:
        print(f"Error: {e}")
        return False, None


if __name__ == '__main__':
    print("=" * 50)
    print("Create User - Facebook Media Aggregator")
    print("=" * 50)
    
    # Get user input
    email = input("Enter email: ").strip()
    if not email:
        print("Email is required!")
        sys.exit(1)
    
    password = input("Enter password: ").strip()
    if not password:
        print("Password is required!")
        sys.exit(1)
    
    name = input("Enter name (optional): ").strip() or None
    
    # Ask if user should be admin
    is_admin_input = input("Make this user an admin? (y/n, default: y): ").strip().lower()
    is_admin = is_admin_input != 'n' and is_admin_input != 'no'
    
    # Create user
    success, user_id = create_user(email, password, name, is_admin)
    if success:
        print("\n✅ User created successfully!")
        print(f"You can now login with:")
        print(f"  Email: {email}")
        print(f"  Password: {password}")
        print(f"  Admin: {'Yes' if is_admin else 'No'}")
        if user_id:
            user_id_str = str(user_id)  # Convert UUID to string
            print(f"\n💡 User ID: {user_id_str}")
            print(f"   You can set ADMIN_USER_ID={user_id_str} in your .env file for reference")
    else:
        print("\n❌ Failed to create user!")
        sys.exit(1)

